### ISSUE TITLE
Dimension mismatch error during training priors

### ISSUE THREAD

**Issue by gzhu06** [michelemancusi/LQVAE-separation#1]
Hi, thanks for the code!

I finished training the LQ-VAE and everything runs smoothly, however, when I tried to train the priors as suggested in the README file, I ran into this error:

>  File "/LQVAE-separation/jukebox/prior/autoregressive.py" line 156, in forward , x = self.x_emb_dropout(x) + self.pos_emb_dropout(self.pos_emb()) + x_cond # Pos emb and dropout RuntimeError: The size of tensor a (1000) must match the size of tensor b (8192) at non-singleton dimension 1

Suggesting that the dimension of self.pos_emb_dropout(self.pos_emb()) (`torch.Size([8192, 1024])`) is different from self.x_emb_dropout(x) (`torch.Size([16, 1000, 1024])`) and x_cond ( `torch.Size([16, 1, 1024])`) 

So in my case, x originally is (`torch.Size([16, 64000, 1])`) (4s inputs) and then after going through an encoder, it becomes  (`torch.Size([16, 1000])`), which is before feeding into the emb.

If I understand this correctly,  the vqvae encoder would downsample the input by 64 times first, so 64000 becomes 1000. But this position embedding context length is set to 8192, so the minimum input audio should be at least 8192*64/sr second(s) right? Can I set a smaller ctx dimension, like 1000? Would this affect the final performance?

**Comment by michelemancusi** [comment]
Sure! You can train priors with different ctx, even with ctx=1000, but you have to be coherent with the dimensions you have highlighted.

**Comment by gzhu06** [comment]
Thanks for the quick reply!

**Comment by michelemancusi** [comment]
No problem, let me know if you solved
