### ISSUE TITLE
UnboundLocalError: local variable 'nll_sum_0' referenced before assignment

### ISSUE THREAD

**Issue by bubblegg** [michelemancusi/LQVAE-separation#2]
Traceback (most recent call last):
  File "bayesian_inference.py", line 828, in <module>
    separate(args)
  File "bayesian_inference.py", line 765, in separate
    emb_width=args.emb_width)
  File "bayesian_inference.py", line 38, in sample_level
    emb_width=emb_width)
  File "bayesian_inference.py", line 69, in sample_single_window
    sum_codebook=sum_codebook, emb_width=emb_width)
  File "bayesian_inference.py", line 103, in sample
    return x_0, x_1, nll_sum_0, nll_sum_1, None
UnboundLocalError: local variable 'nll_sum_0' referenced before assignment

**Comment by EmilianPostolache** [comment]
Sampling a context greater than `n_context` is not supported at the moment. You should set `sample_tokens` to a  value less than or equal to `8192` which is the `n_context` of the prior.

**Comment by bubblegg** [comment]
Oh okay, thank you, what do you recommend for getting longer results, splitting tracks into more samples?

**Comment by michelemancusi** [comment]
Yes, you have to split the song in more chunks

**Comment by bubblegg** [comment]
Still got the same error after setting --sample_tokens 8192

**Comment by bubblegg** [comment]
Okay, putting lover value helped! Thank you!

**Comment by EmilianPostolache** [comment]
Yes, that works! I have fixed the code in [f6e14cd](https://github.com/michelemancusi/LQVAE-separation/commit/f6e14cd625d02332ace593b8779f652c416d50c9) in order to make it work with `sample_tokens = n_context`. From our experiments, we noticed however that keeping the sampling window around ~ 1024 tokens resulted in better outputs.
